version: "3.8"

services:
  nodesight:
    # build:
    #   context: .
    #   dockerfile: docker/Dockerfile
    image: mgarnier11/nodesight:latest
    ports:
      - "3000:3000"
    privileged: true
    volumes:
      - /:/mnt/host:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
