build autosaver amd64:
  extends: .build-template
  tags:
    - amd64
  variables:
    PROJECT_NAME: autosaver
    TAG_NAME: amd64

build autosaver arm64:
  extends: .build-template
  tags:
    - arm64
  variables:
    PROJECT_NAME: autosaver
    TAG_NAME: arm64

publish autosaver:
  extends: .publish-template
  variables:
    PROJECT_NAME: autosaver
  needs:
    - build autosaver amd64
    - build autosaver arm64
