build autosaver amd64:
  extends: .build-template
  variables:
    PROJECT_NAME: autosaver
    TAG_NAME: amd64

build autosaver arm64:
  extends: .build-template
  variables:
    PROJECT_NAME: autosaver
    TAG_NAME: arm64

manifest autosaver:
  extends: .manifest-template
  variables:
    PROJECT_NAME: autosaver
