default-cifs: &default-cifs
  user: mgarnier
  password: password
  ip: 127.0.0.1
  port: 4201

config:
  directories:
    - type: local
      srcPath: /test/src/1
      destPath: /test/dest/1
    - type: local
      srcPath: /test/src/2
      destPath: /test/dest/2
    - type: cifs
      hostPath: /share/home
      mountPath: /test/dest/3
      <<: *default-cifs
  rsync:
    type: cifs
    hostPath: /share/rsync
    mountPath: /test/dest
    <<: *default-cifs
