# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

dotenv:
  - .env

includes:
  go-proxy:
    taskfile: ./apps/go-proxy/taskfile.yml
    dir: ./apps/go-proxy
    optional: true
  home-cli:
    taskfile: ./apps/home-cli/taskfile.yml
    dir: ./apps/home-cli
    optional: true
  mineager:
    taskfile: ./apps/mineager/taskfile.yml
    dir: ./apps/mineager
    optional: true
# tasks:
#   build-test-proxy:
#     dir: tests/test-proxy
#     cmds:
#       - go build -o ../../bin/test-proxy
#     silent: true
#   start-test-proxy:
#     dir: tests/test-proxy
#     cmds:
#       - task: build-test-proxy
#       - ../../bin/test-proxy
#     silent: true
