stages:
  - build

build:
  image: jdrouet/docker-with-buildx:stable
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u mgarnier11 -p $DOCKER_HUB_TOKEN
    - docker buildx create --use
    - >
      if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
        docker buildx build --platform linux/amd64,linux/arm/v8 -t mgarnier11/stats-api -f docker/Dockerfile . --push
      else 
        docker buildx build --platform linux/amd64,linux/arm/v8 -t mgarnier11/stats-api:$CI_COMMIT_REF_NAME -f docker/Dockerfile . --push
      fi
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
