build stats-api amd64:
  extends: .build-template
  variables:
    PROJECT_NAME: stats-api
    TAG_NAME: amd64

build stats-api arm64:
  extends: .build-template
  tags:
    - arm64
  variables:
    PROJECT_NAME: stats-api
    TAG_NAME: arm64

publish stats-api:
  extends: .publish-template
  variables:
    PROJECT_NAME: stats-api
  needs:
    - build stats-api amd64
    - build stats-api arm64
