build stats-api:
  stage: build
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 -t mgarnier11/stats-api -f apps/stats-api/docker/Dockerfile . --push
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - apps/stats-api/**/*
    - when: manual
