build traefik-conf amd64:
  extends: .build-template
  tags:
    - amd64
  variables:
    PROJECT_NAME: traefik-conf
    TAG_NAME: amd64

build traefik-conf arm64:
  extends: .build-template
  tags:
    - arm64
  variables:
    PROJECT_NAME: traefik-conf
    TAG_NAME: arm64

publish traefik-conf:
  extends: .publish-template
  variables:
    PROJECT_NAME: traefik-conf
  needs:
    - build traefik-conf amd64
    - build traefik-conf arm64
