services:
  orchestrator:
    image: mgarnier11/orchestrator
    container_name: orchestrator
    ports:
      - 3000:3000
    environment:
      - COMPOSE_ENV_FILES=/compose/env.env,/compose/ports.env
      - COMPOSE_FOLDER=/compose/stacks
      - STACK_FILE=/compose/stack.yml
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - orchestrator:/compose
      - ${SSH_AUTH_SOCK}:/ssh-agent

volumes:
  orchestrator:
    name: orchestrator
    driver: local
    driver_opts:
      type: cifs
      o: 'rw,username=${SMB_USER},password=${SMB_PWD},iocharset=utf8,uid=1000,sec=ntlmv2,file_mode=0777,dir_mode=0777'
      device: //192.168.0.254/SSD1/docker-data/orchestrator
