# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  download:
    dir: ./src
    cmds:
      - go mod download
  build-src:
    dir: ./src
    cmds:
      - go build -o ../dist/orchestrator
  build:
    dir: ./src
    cmds:
      - GOOS=windows GOARCH=amd64 go build -o ../dist/orchestrator-windows-amd64.exe
      - GOOS=linux GOARCH=amd64 go build -o ../dist/orchestrator-linux-amd64
      - GOOS=linux GOARCH=arm go build -o ../dist/orchestrator-linux-arm
      - go build -o ../dist/orchestrator
  start:
    dir: ./src
    env:
      ENV_FILE_PATH: /mnt/dev/home-monorepo/apps/orchestrator/.env
    cmds:
      - task: build
      - ../dist/orchestrator {{.CLI_ARGS}}
