name: home-devcontainer

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - 2223:2222
      - 2224:8080
    environment:
      - NODE_VERSION=22
      - GIT_EMAIL=mgarnier11@gmail.com
      - GIT_NAME=mgarnier11
      - ORCHESTRATOR_API_URL=https://orchestrator.int.mgarnier11.fr
      - DEVCONTAINER_TESTAZE=patate
    secrets: 
      - SSH_PRIVATE_KEY
    volumes:
      - mnt-dev:/mnt/dev
# - ~/.ssh/id_rsa:/tmp/SSH_PRIVATE_KEY:ro


volumes:
  mnt-dev:

secrets:
  SSH_PRIVATE_KEY:
    file: ~/.ssh/id_rsa
