name: home-devcontainer

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - 2223:2222
      - 2224:8080
    environment:
      - NODE_VERSION=22
      - GIT_EMAIL=mgarnier11@gmail.com
      - GIT_NAME=mgarnier11
    secrets: 
      - SSH_PRIVATE_KEY
    volumes:
      - mnt-dev:/mnt/dev
      - mnt-docker-data-zephyr:/mnt/docker-data/zephyr

volumes:
  mnt-dev:
  mnt-docker-data-zephyr:
    driver: local
    driver_opts:
      type: cifs
      device: //100.64.98.97/share/docker-data
      o: rw,vers=3.02,mfsymlinks,cache=none,username=mgarnier,password=password,iocharset=utf8,uid=1000,sec=ntlmv2,file_mode=0777,dir_mode=0777

secrets:
  SSH_PRIVATE_KEY:
    file: ~/.ssh/id_rsa
