.rules-nodesight: &rules-nodesight
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - apps/nodesight/**/*

build nodesight amd64:
  stage: build
  script:
    - docker build -t mgarnier11/nodesight:amd64 -f apps/nodesight/docker/Dockerfile . --push
  <<: *rules-nodesight

build nodesight arm64:
  stage: build
  tags:
    - arm64
  script:
    - docker build -t mgarnier11/nodesight:arm64 -f apps/nodesight/docker/Dockerfile . --push
  <<: *rules-nodesight

manifest nodesight:
  stage: manifest
  script:
    - docker manifest create mgarnier11/nodesight mgarnier11/nodesight:amd64 mgarnier11/nodesight:arm64
    - docker manifest push mgarnier11/nodesight
  <<: *rules-nodesight
