build nodesight amd64:
  extends: .build-template
  variables:
    PROJECT_NAME: nodesight
    TAG_NAME: amd64

build nodesight amd64-nvidia:
  extends: .build-template
  variables:
    PROJECT_NAME: nodesight
    TAG_NAME: amd64-nvidia

build nodesight arm64:
  extends: .build-template
  tags:
    - arm64
  variables:
    PROJECT_NAME: nodesight
    TAG_NAME: arm64

publish nodesight:
  extends: .publish-template
  variables:
    PROJECT_NAME: nodesight
  needs:
    - build nodesight amd64
    - build nodesight arm64
    - build nodesight amd64-nvidia
