build nodesight:
  stage: build
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 -t mgarnier11/nodesight -f apps/nodesight/docker/Dockerfile . --push
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - apps/nodesight/**/*
    - when: manual
