build node-proxy amd64:
  extends: .build-template
  tags:
    - amd64
  variables:
    PROJECT_NAME: node-proxy
    TAG_NAME: amd64

build node-proxy arm64:
  extends: .build-template
  tags:
    - arm64
  variables:
    PROJECT_NAME: node-proxy
    TAG_NAME: arm64

publish node-proxy:
  extends: .publish-template
  variables:
    PROJECT_NAME: node-proxy
  needs:
    - build node-proxy amd64
    - build node-proxy arm64
