#!/usr/bin/env bash

echo "Running pre-commit hook"

# Check if any .ts or .html or DOCKERFILE files in apps/* are modified
FILES_MODIFIED=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^apps/.*\.ts(x)?$|^apps/.*\.html$|^apps/.*Dockerfile$')

# If .ts files are modified, run the commands
if [ ! -z "$FILES_MODIFIED" ]; then
  # List all files that will be committed and increment versions if they are in apps/*
  
  echo "$FILES_MODIFIED" \
    | grep -E '^apps/.*' \
    | xargs -I {} dirname {} \
    | cut -d/ -f1-2 \
    | sort -u \
    | xargs -I {} sh -c 'cd {} && echo "{}" && npm run patch-version && git add package.json'
fi

