# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:
    dir: ./src
    cmds:
      - go build -o ../dist/go-proxy

  start:
    cmds:
      - task build
      - ./dist/go-proxy

  test:
    dir: ./src
    cmds:
      - go test -v ./...
