name: "Build and publish app"
run-name: "Build and publish ${{ inputs.app-to-publish }}"

on:
  workflow_call:
    inputs:
      app-to-publish:
        description: "The name of the application to publish"
        required: true
        type: string
      version-upgrade:
        description: "How to upgrade the version"
        required: true
        type: string

jobs:
  get-version:
    runs-on: ubuntu-latest
    name: Get version
    outputs:
      new-app-version: ${{ steps.increment-version.outputs.new-version }}
    steps:
      - name: Get versions of app from docker hub
        uses: mgarnier11/gh-actions/get-docker-versions@latest
        id: get-docker-versions
        with:
          api-url: https://hub.docker.com/v2/repositories
          image-author: mgarnier11
          image-name: ${{ inputs.app-to-publish }}
      - name: Increment the version
        uses: mgarnier11/gh-actions/increment-version@latest
        id: increment-version
        with:
          version: ${{ steps.get-docker-versions.outputs.latest-version }}
          upgrade: ${{ inputs.version-upgrade }}
  build-amd64:
    runs-on: linux/amd64
    needs: get-version
    name: Build amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build app for amd64
        uses: ./.github/actions/build
        with:
          app-name: ${{ inputs.app-to-publish }}
          version: ${{ needs.get-version.outputs.new-app-version }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  build-arm64:
    runs-on: linux/arm64
    needs: get-version
    name: Build arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build app for arm64
        uses: ./.github/actions/build
        with:
          app-name: ${{ inputs.app-to-publish }}
          version: ${{ needs.get-version.outputs.new-app-version }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    needs:
      - get-version
      - build-amd64
      - build-arm64
    name: Publish
    steps:
      - run: echo "Publishing ${{ inputs.app-to-publish }} version ${{ needs.get-version.outputs.new-app-version }}"
