name: Publish version
run-name: Publish version for an application

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: mgarnier11/gh-actions/get-docker-versions@latest
        id: get-docker-versions
        with:
          api-url: https://hub.docker.com/v2/repositories
          image-author: mgarnier11
          image-name: autosaver
          only-latest: true
      - name: Print all the versions
        run: echo "${{ steps.get-docker-versions.outputs.all-versions }}"
      - name: Print all the tags
        run: echo "${{ steps.get-docker-versions.outputs.all-tags }}"
      - name: Print the latest version
        run: echo "${{ steps.get-docker-versions.outputs.latest-version }}"
      - name: Increment the version
        uses: mgarnier11/gh-actions/increment-version@latest
        id: increment-version
        with:
          version: ${{ steps.get-docker-versions.outputs.latest-version }}
          upgrade: patch
      - name: Print the new version
        run: echo "${{ steps.increment-version.outputs.new-version }}"
