name: Publish version V2
run-name: "Inc: ${{ inputs.version-upgrade }} - Publish: ${{ inputs.apps }}"

on:
  workflow_dispatch:
    inputs:
      version-upgrade:
        description: "How to upgrade the version"
        required: true
        type: choice
        options:
          - "false"
          - "patch"
          - "minor"
          - "major"
      apps:
        description: "Applications to publish"
        required: true
        type: string
        default: "autosaver,cron-runner,dashboard,go-proxy,home-cli,node-proxy,nodesight,stats-api,syslog-app,traefik-conf"
      test:
        description: "Test"
        required: true
        type: boolean
        default: true
      
jobs:
  get-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix-apps: ${{ steps.set-matrix-output.outputs.matrix-apps }}
    steps:
      - id: set-matrix-output
        run: |
          apps=($(echo ${{ inputs.apps }} | tr "," "\n"))
          matrix_apps=$(printf "\"%s\"," "${apps[@]}")
          matrix_apps="[${matrix_apps%,}]"
          echo "matrix-apps=$matrix_apps" >> $GITHUB_OUTPUT
  run-publish-workflow:
    name: ${{ matrix.app }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running ${{ matrix.app }} - ${{ inputs.version-upgrade }}"
    # uses: ./.github/workflows/build-and-publish-app.yml
    # with:
    #   app-to-publish: ${{ matrix.app }}
    #   version-upgrade: ${{ inputs.version-upgrade }}
    # secrets: inherit
    needs: get-matrix
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJson(needs.get-matrix.outputs.matrix-apps) }}