name: Publish version
run-name: Publish version for an application

on:
  workflow_dispatch:
    inputs:
      version-upgrade:
        description: "How to upgrade the version"
        required: true
        type: choice
        options:
          - "false"
          - "patch"
          - "minor"
          - "major"
      app-name:
        description: "The name of the application"
        required: true
        default: "none"
        type: choice
        options:
          - "autosaver"
          - "dashboard"
          - "node-proxy"
          - "nodesight"
          - "stats-api"
          - "syslog-app"
          - "traefik-conf"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: mgarnier11/gh-actions/get-docker-versions@latest
        id: get-docker-versions
        with:
          api-url: https://hub.docker.com/v2/repositories
          image-author: mgarnier11
          image-name: existePas
      - name: Print all the versions
        run: echo "${{ steps.get-docker-versions.outputs.all-versions }}"
      - name: Print all the tags
        run: echo "${{ steps.get-docker-versions.outputs.all-tags }}"
      - name: Print the latest version
        run: echo "${{ steps.get-docker-versions.outputs.latest-version }}"
      - name: Increment the version
        uses: mgarnier11/gh-actions/increment-version@latest
        id: increment-version
        with:
          version: ${{ steps.get-docker-versions.outputs.latest-version }}
          upgrade: patch
      - name: Print the new version
        run: echo "${{ steps.increment-version.outputs.new-version }}"
