name: Publish app
run-name: '${{ inputs.app }} : ${{ inputs.version-upgrade }}'

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Application to publish'
        required: true
        type: choice
        options:
          - 'autoscaler'
          - 'cron-runner'
          - 'dashboard'
          - 'go-autosaver'
          - 'go-proxy'
          - 'home-cli'
          - 'home-container'
          - 'nodesight'
          - 'stats-api'
          - 'traefik-conf'
      version-upgrade:
        description: 'How to upgrade the version'
        required: true
        type: choice
        options:
          - 'false'
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  get-version:
    runs-on: ubuntu-latest
    name: Get version
    outputs:
      new-app-version: ${{ steps.increment-version.outputs.new-version }}
    steps:
      - name: Get versions of app from docker hub
        uses: mgarnier11/gh-actions/get-docker-versions@latest
        id: get-docker-versions
        with:
          api-url: https://hub.docker.com/v2/repositories
          image-author: mgarnier11
          image-name: ${{ inputs.app }}
      - name: Increment the version
        uses: mgarnier11/gh-actions/increment-version@latest
        id: increment-version
        with:
          version: ${{ steps.get-docker-versions.outputs.latest-version }}
          upgrade: ${{ inputs.version-upgrade }}
  build:
    if: ${{ inputs.app != 'home-container' }}
    runs-on: linux/${{ matrix.platform }}
    needs: get-version
    name: Build ${{ needs.get-version.outputs.new-app-version }} on ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build application
        shell: bash
        run: bash build-app.sh --name ${{ inputs.app }} --version ${{ needs.get-version.outputs.new-app-version }} --tag ${{ matrix.platform }}
      - name: Push application runtime
        shell: bash
        run: docker push mgarnier11/${{ inputs.app }}:${{ matrix.platform }}
  publish:
    runs-on: ubuntu-latest
    needs:
      - get-version
      - build
    name: Publish ${{ needs.get-version.outputs.new-app-version }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish version ${{ needs.get-version.outputs.new-app-version }} for ${{ inputs.app }}
        run: >
          docker buildx imagetools create
          --tag mgarnier11/${{ inputs.app }}:latest
          --tag mgarnier11/${{ inputs.app }}:${{ needs.get-version.outputs.new-app-version }}
          mgarnier11/${{ inputs.app }}:amd64
          mgarnier11/${{ inputs.app }}:arm64
  build-and-publish-home-container:
    runs-on: linux/amd64
    if: ${{ inputs.app == 'home-container' }}
    needs: get-version
    name: Build and publish home-container-${{ needs.get-version.outputs.new-app-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build home-container
        shell: bash
        run: bash build-home-container.sh --version ${{ needs.get-version.outputs.new-app-version }}
      - name: Push home-container
        shell: bash
        run: docker push mgarnier11/home-container --all-tags
